version: 2
jobs:
  build:
    working_directory: ~/cci-demo-phoenix
    docker:
      - image: elixir:1.8.0
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-mix-deps
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - save_cache:
          key: v1-mix-deps
          paths:
            - _build
            - deps
      - run: mix test
